#pragma once
#include "CoreMinimal.h"
#include "EMappinType.generated.h"

UENUM(BlueprintType)
enum class EMappinType : uint8 {
    None,
    MainQuest,
    SideQuest,
    POIQuest,
    StoryQuest,
    StoryQuestAtDay,
    StoryQuestAtNight,
    StoryQuestTimeSensitive,
    StoryQuestTimeSensitiveAtDay,
    StoryQuestTimeSensitiveAtNight,
    NanoPOIQuest,
    NanoPOIQuestAtDay,
    NanoPOIQuestAtNight,
    MainQuestStart,
    SideQuestStart,
    POIQuestStart,
    StoryQuestStart,
    StoryQuestStartAtDay,
    StoryQuestStartAtNight,
    NanoPOIQuestStart,
    NanoPOIQuestStartAtDay,
    NanoPOIQuestStartAtNight,
    Player,
    User,
    FastTravel,
    Village,
    House,
    TimeSkip,
    Pillory,
    NanoPoiDestroyedShrine,
    NanoPoiPixie,
    NanoPoiAoHRemnants,
    NanoPoiTower,
    NanoPoiHauntedPlace,
    NanoPoiBrencisFlag,
    NanoPoiBrencisCheckpoint,
    NanoPoiEnvirostorytellingInHouses,
    NanoPoiHumanEnemyCamp,
    NanoPoiBanditCamp,
    NanoPoiBrencisMenCamp,
    NanoPoiHeadhunters,
    NanoPoiTransport,
    NanoPoiMonsterNest,
    NanoPoiManVsMan,
    NanoPoiManVsNature,
    NanoPoiGate,
    NPCGeneralStore,
    NPCBlacksmith,
    NPCArmorer,
    NPCMedic,
    NPCMagicVendor,
    NPCTavern,
    NPCSilverTrader,
    NPCFoodTrader,
    NPCSwordmaster,
    NPCJeweleryTrader,
    CustomOpenWorld,
    Count,
    First = MainQuest,
    Last = CustomOpenWorld,
    OpenWorldFirst = FastTravel,
    OpenWorldLast = CustomOpenWorld,
    QuestFirst = MainQuest,
    QuestLast = NanoPOIQuestAtNight,
    QuestStartFirst = MainQuestStart,
    QuestStartLast = NanoPOIQuestStartAtNight,
    NanoPoiFirst = NanoPoiDestroyedShrine,
    NanoPoiLast = NanoPoiGate,
    NpcFirst = NPCGeneralStore,
    NpcLast = NPCJeweleryTrader,
};

