using UnrealBuildTool;

public class Dawnwalker : ModuleRules {
    public Dawnwalker(ReadOnlyTargetRules Target) : base(Target) {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
        bLegacyPublicIncludePaths = false;
        ShadowVariableWarningLevel = WarningLevel.Warning;
        
        PublicDependencyModuleNames.AddRange(new string[] {
            "AIModule",
            "AnimationBudgetAllocator",
            "CinematicCamera",
            "CommonUI",
            "Core",
            "CoreUObject",
            "DeveloperSettings",
            "DialogueSystem",
            "DogwoodAI",
            "DogwoodAICore",
            "DogwoodAbilitySystem",
            "DogwoodAnim",
            "DogwoodCharacterDevelopment",
            "DogwoodCombat",
            "DogwoodDebug",
            "DogwoodDialogue",
            "DogwoodFocus",
            "DogwoodGlossary",
            "DogwoodInventory",
            "DogwoodMap",
            "DogwoodNanitePrefetch",
            "DogwoodQuest",
            "DogwoodStats",
            "DogwoodSystem",
            "DogwoodUI",
            "DogwoodUtil",
            "DogwoodVampireHunger",
            "DogwoodWorld",
            "Engine",
            "EnhancedInput",
            "FactsDB",
            "Flow",
            "GamepadVibration",
            "GameplayAbilities",
            "GameplayTags",
            "GameplayTasks",
            "InputCore",
            "LevelSequence",
            "MediaAssets",
            "MotionWarping",
            "NavigationSystem",
            "Niagara",
            "NodeRuntime",
            "Persistency",
            "Population",
            "Quest",
            "RebelAI",
            "RebelAudio",
            "RebelCamera",
            "RebelFoliage",
            "RebelFormation",
            "RebelHorse",
            "RebelLoading",
            "RebelLocomotion",
            "RebelRoads",
            "RebelSettings",
            "RebelSpatialSystem",
            "RebelTableRow",
            "RebelUtils",
            "SkyCreatorPlugin",
            "Slate",
            "SlateCore",
            "StateTreeModule",
            "UMG",
        });
    }
}
